# Fondo (Oscuro profundo)
background            #0f0000

# Texto (Blanco puro para máximo contraste)
foreground            #ededed

# Selección (Para que resalte la letra sobre el fondo)
selection_foreground  #ffffff
selection_background  #7a0000

# Paleta de Colores (Rojo Porsche #b70001 — profundo y elegante)

# black
color0                #1a0000
color8                #4a0000

# red (Rojos principales)
color1                #b70001  # Rojo Porsche principal
color9                #d41919  # Rojo un tono más vivo

# green
color2                #58b858
color10               #85e085

# yellow
color3                #d9a03c
color11               #ffb84d

# blue
color4                #5f8fd7
color12               #82b1ff

# magenta
color5                #c94f8a
color13               #e57ab0

# cyan
color6                #3fb8b8
color14               #66dede

# white
color7                #d1d1d1
color15               #ffffff

# Cursor y otros
cursor                #b70001
active_border_color   #b70001
inactive_border_color #2a0000
url_color             #ffa05f
