# Fondo (Oscuro profundo)
background            #0f0000

# Texto (Blanco grisáceo para alto contraste y legibilidad)
foreground            #e0e0e0

# Selección (Para que resalte la letra sobre el fondo)
selection_foreground  #ffffff
selection_background  #990000

# Paleta de Colores (Rojos Chillantes e Intensos)

# black
color0                #1a0000
color8                #4a0000

# red (Rojos principales - Intensidad Máxima)
color1                #ff0000  # Rojo puro neón
color9                #ff1a1a  # Rojo aún más chillante

# green (Ahora un rojo neón muy saturado)
color2                #ff3333
color10               #ff6666

# yellow (Naranja/Rojo fuego intenso)
color3                #ff4d00
color11               #ff8000

# blue (Rojo carmesí saturado)
color4                #ff0033
color12               #ff335c

# magenta (Rojo rosado chillante)
color5                #ff0066
color13               #ff337e

# cyan (Rojo/Naranja muy vivo)
color6                #ff6600
color14               #ff9933

# white
color7                #d1d1d1
color15               #ffffff

# Cursor y otros
cursor                #ff0000
active_border_color   #ff0000
inactive_border_color #2a0000
url_color             #ff3333
