set -g base-index 1
setw -g pane-base-index 1

set -g status-style "bg=default,fg=#777777"
set -g status-left ""
set -g status-right ""
set -g status-justify left
set -g status-left-length 0
set -g status-right-length 0

set -g window-status-format "#[fg=#555555]#I:#W "
set -g window-status-current-format "#[fg=#ffffff,bold]#I:#W "
set -g window-status-separator ""

set -g pane-border-style "fg=#333333"
set -g pane-active-border-style "fg=#777777"
