$font = JetBrainsMono Nerd Font

general {
    hide_cursor = false
    immediate_render = true
}

auth {
    fingerprint {
        enabled = true
        ready_message = Escanea tu huella para desbloquear
        present_message = Escaneando...
        retry_delay = 250
    }
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = screenshot
    blur_size = 6
    blur_passes = 3
    contrast = 0.9
    brightness = 0.5
    color = rgba(10, 10, 12, 0.75)
}

input-field {
    monitor =
    size = 350, 50
    outline_thickness = 1
    inner_color = rgba(22, 22, 22, 0)
    outer_color = rgba(0, 0, 0, 0)
    check_color = rgba(0, 255, 153, 0.9) rgba(255, 102, 51, 0.9) 120deg
    fail_color = rgba(139, 0, 0, 0.9)
    font_color = rgb(255, 255, 255)
    fade_on_empty = false
    rounding = 8
    font_family = $font
    placeholder_text = 
    fail_text = $PAMFAIL
    dots_spacing = 0.5
    position = 0, -150
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    font_size = 200
    font_family = Old London
    color = rgb(245, 235, 235)
    shadow_color = rgba(183, 0, 1, 0.8)
    shadow_size = 10
    position = 0, 0
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    font_size = 24
    font_family = $font
    color = rgb(230, 220, 220)
    position = 0, 150
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:5000] cat /sys/class/power_supply/BAT*/capacity 2>/dev/null | head -n 1 | awk '{print $1"%"}'
    color = rgba(200, 200, 200, 1.0)
    font_size = 16
    font_family = $font
    position = 30, 30
    halign = left
    valign = bottom
}
