[ids]
*

[main]
leftalt = overload(numpad, leftalt)
enter = overload(nav, enter)

[nav]
a = left
s = left
d = down
f = right
e = up

[numpad]
# Operadores
a = kpplus
s = kpminus
d = kpasterisk
f = kpslash
g = kpequal
p = kpequal

# Números
m = 1
comma = 2
dot = 3
j = 4
k = 5
l = 6
u = 7
i = 8
o = 9
semicolon = 0
